### ISSUE TITLE
back constraint?

### ISSUE THREAD

**Issue by TuBui** [SheffieldML/vargplvm#3]
Thank you for sharing the code. I see that back constraint is no longer supported in vargplvm. Is there any reason behind it?

**Comment by adamian** [comment]
It's a bit more tricky to implement it in vargplvm, because you don't just have latent points X, but instead a latent approx. posterior q(X). If you really need the back-constraints, you can either use the dynamical vargplvm version where you set the top node to be the same as your data (hence creating an autoencoder), or you can follow this approach: http://arxiv.org/pdf/1511.06455v1.pdf
Hope that helps.
